[general]
secret_key = ""
database_uri = "sqlite:///db.sqlite3"
max_sessions = 60
cdms = ["cdm_identifier"]
system_cdms = ["cdm_identifier"]
guild_id = ""
verified_role_id = ""
login_disabled = false
log_format = "[%(asctime)s] [%(name)s] [%(funcName)s:%(lineno)d] %(levelname)s: %(message)s"
log_date_format = "%I:%M:%S"

[api]
host = "0.0.0.0"
port = 8080
base_url = ""

[oauth]
client_id = ""
client_secret = ""
redirect_url = ""

[[url_blacklist]]
url = ".*my\\.awesome\\.site\\.com.*"
partial = true

[[url_blacklist]]
url = "https://example.com/some_page_to_block"
partial = false

[[external_build_info]]
buildinfo = "build_info_string"
url = "https://example.com/api"
token = "s3cr$t"
