"""create_prd

Revision ID: 51d65f145c1f
Revises: 592b912adf54
Create Date: 2024-12-02 13:40:39.900188

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51d65f145c1f"
down_revision: Union[str, None] = "592b912adf54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = "592b912adf54"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "hash",
            sa.String(length=255, collation="utf8mb4_general_ci"),
            nullable=False,
        ),
        sa.Column("prd", sa.Text(), nullable=False),
        sa.Column(
            "uploaded_by",
            sa.String(length=255, collation="utf8mb4_general_ci"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
    )
    op.create_table(
        "user_prd",
        sa.Column(
            "user_id",
            sa.String(length=255, collation="utf8mb4_general_ci"),
            nullable=False,
        ),
        sa.Column(
            "device_hash",
            sa.String(length=255, collation="utf8mb4_general_ci"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["device_hash"], ["prds.hash"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_prd")
    op.drop_table("prds")
    # ### end Alembic commands ###
