"""Add traffic logging

Revision ID: ed93e0135889
Revises: 4dcee16042d2
Create Date: 2025-07-07 13:18:50.609291

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed93e0135889"
down_revision: Union[str, None] = "4dcee16042d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "traffic_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "user_id",
            sa.String(length=255, collation="utf8mb4_general_ci"),
            nullable=True,
        ),
        sa.Column(
            "path", sa.String(length=255, collation="utf8mb4_general_ci"), nullable=True
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(collation="utf8mb4_general_ci"), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("traffic_logs")
    # ### end Alembic commands ###
