# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16license_protocol.proto\x12\x1bpywidevine_license_protocol\"\xf6\x05\n\x10WidevinePsshData\x12\x0f\n\x07key_ids\x18\x02 \x03(\x0c\x12\x12\n\ncontent_id\x18\x04 \x01(\x0c\x12\x1b\n\x13\x63rypto_period_index\x18\x07 \x01(\r\x12\x19\n\x11protection_scheme\x18\t \x01(\r\x12\x1d\n\x15\x63rypto_period_seconds\x18\n \x01(\r\x12H\n\x04type\x18\x0b \x01(\x0e\x32\x32.pywidevine_license_protocol.WidevinePsshData.Type:\x06SINGLE\x12\x14\n\x0ckey_sequence\x18\x0c \x01(\r\x12\x11\n\tgroup_ids\x18\r \x03(\x0c\x12P\n\rentitled_keys\x18\x0e \x03(\x0b\x32\x39.pywidevine_license_protocol.WidevinePsshData.EntitledKey\x12\x15\n\rvideo_feature\x18\x0f \x01(\t\x12N\n\talgorithm\x18\x01 \x01(\x0e\x32\x37.pywidevine_license_protocol.WidevinePsshData.AlgorithmB\x02\x18\x01\x12\x14\n\x08provider\x18\x03 \x01(\tB\x02\x18\x01\x12\x16\n\ntrack_type\x18\x05 \x01(\tB\x02\x18\x01\x12\x12\n\x06policy\x18\x06 \x01(\tB\x02\x18\x01\x12\x1b\n\x0fgrouped_license\x18\x08 \x01(\x0c\x42\x02\x18\x01\x1az\n\x0b\x45ntitledKey\x12\x1a\n\x12\x65ntitlement_key_id\x18\x01 \x01(\x0c\x12\x0e\n\x06key_id\x18\x02 \x01(\x0c\x12\x0b\n\x03key\x18\x03 \x01(\x0c\x12\n\n\x02iv\x18\x04 \x01(\x0c\x12&\n\x1a\x65ntitlement_key_size_bytes\x18\x05 \x01(\r:\x02\x33\x32\"5\n\x04Type\x12\n\n\x06SINGLE\x10\x00\x12\x0f\n\x0b\x45NTITLEMENT\x10\x01\x12\x10\n\x0c\x45NTITLED_KEY\x10\x02\"(\n\tAlgorithm\x12\x0f\n\x0bUNENCRYPTED\x10\x00\x12\n\n\x06\x41\x45SCTR\x10\x01*8\n\x0bLicenseType\x12\r\n\tSTREAMING\x10\x01\x12\x0b\n\x07OFFLINE\x10\x02\x12\r\n\tAUTOMATIC\x10\x03\x42$\n com.rlaphoenix.pywidevine.protosH\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'license_protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.rlaphoenix.pywidevine.protosH\003'
  _WIDEVINEPSSHDATA.fields_by_name['algorithm']._options = None
  _WIDEVINEPSSHDATA.fields_by_name['algorithm']._serialized_options = b'\030\001'
  _WIDEVINEPSSHDATA.fields_by_name['provider']._options = None
  _WIDEVINEPSSHDATA.fields_by_name['provider']._serialized_options = b'\030\001'
  _WIDEVINEPSSHDATA.fields_by_name['track_type']._options = None
  _WIDEVINEPSSHDATA.fields_by_name['track_type']._serialized_options = b'\030\001'
  _WIDEVINEPSSHDATA.fields_by_name['policy']._options = None
  _WIDEVINEPSSHDATA.fields_by_name['policy']._serialized_options = b'\030\001'
  _WIDEVINEPSSHDATA.fields_by_name['grouped_license']._options = None
  _WIDEVINEPSSHDATA.fields_by_name['grouped_license']._serialized_options = b'\030\001'
  _globals['_LICENSETYPE']._serialized_start=816
  _globals['_LICENSETYPE']._serialized_end=872
  _globals['_WIDEVINEPSSHDATA']._serialized_start=56
  _globals['_WIDEVINEPSSHDATA']._serialized_end=814
  _globals['_WIDEVINEPSSHDATA_ENTITLEDKEY']._serialized_start=595
  _globals['_WIDEVINEPSSHDATA_ENTITLEDKEY']._serialized_end=717
  _globals['_WIDEVINEPSSHDATA_TYPE']._serialized_start=719
  _globals['_WIDEVINEPSSHDATA_TYPE']._serialized_end=772
  _globals['_WIDEVINEPSSHDATA_ALGORITHM']._serialized_start=774
  _globals['_WIDEVINEPSSHDATA_ALGORITHM']._serialized_end=814
# @@protoc_insertion_point(module_scope)
